# Generated by Django 2.2.4 on 2019-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('amount_of_quantites', models.PositiveIntegerField(default=0, verbose_name='Amount Of Quantites')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Unit price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
