# Generated by Django 2.2.4 on 2019-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20190810_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit price'),
        ),
    ]
